# Generated by Django 6.0.4 on 2026-05-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_add_gateway_signal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantelemetry',
            name='fire_alarm',
            field=models.BooleanField(default=False, verbose_name='Tín hiệu báo cháy'),
        ),
        migrations.AddField(
            model_name='fanunit',
            name='last_fire_alarm',
            field=models.BooleanField(default=False, verbose_name='Tín hiệu báo cháy'),
        ),
    ]
