# Generated by Django 6.0.4 on 2026-05-23 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_fantelemetry_fire_alarm_fanunit_last_fire_alarm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(max_length=20, verbose_name='Loại lệnh')),
                ('payload', models.JSONField(verbose_name='Dữ liệu lệnh')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('fan_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_requests', to='dashboard.fanunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu điều khiển',
                'verbose_name_plural': 'Danh sách yêu cầu điều khiển',
                'ordering': ['-created_at'],
            },
        ),
    ]
