# Generated by Django 6.0.4 on 2026-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_commandrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedCOSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=20, unique=True, verbose_name='Mã cảm biến')),
                ('name', models.CharField(max_length=100, verbose_name='Tên cảm biến')),
                ('operating_hours', models.FloatField(default=0, verbose_name='Số giờ hoạt động')),
                ('is_active', models.BooleanField(default=False, verbose_name='Kích hoạt')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Mô tả/Vị trí')),
            ],
            options={
                'verbose_name': 'Cảm biến CO Giả lập',
                'verbose_name_plural': 'Danh sách cảm biến CO',
                'ordering': ['sensor_id'],
            },
        ),
    ]
