# Generated by Django 6.0.4 on 2026-05-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_simulatedcosensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatedcosensor',
            name='zone',
            field=models.CharField(default='B1', max_length=50, verbose_name='Khu vực'),
        ),
    ]
