# Generated by Django 6.0.4 on 2026-05-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_simulatedcosensor_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatedcosensor',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Lần cập nhật cuối'),
        ),
        migrations.AlterField(
            model_name='simulatedcosensor',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Trạng thái'),
        ),
    ]
