# Generated by Django 6.0.4 on 2026-06-01 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_simulatedcosensor_last_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Hành động')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.TextField(blank=True, verbose_name='Chi tiết')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='dashboard.fanunit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký người dùng',
                'verbose_name_plural': 'Nhật ký người dùng',
                'ordering': ['-timestamp'],
            },
        ),
    ]
